name: Documentation

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install sphinx sphinx-design sphinx-gallery pydata-sphinx-theme numpydoc sphinxcontrib-sass sphinx-remove-toctrees matplotlib jinja2

      - name: Build the documentation
        run: |
          sphinx-apidoc -f -o docs/source mvpy/
          sphinx-build -b html docs/ docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
